apiVersion: v1
kind: Service
metadata:
  name: deploy-latest-application
spec:
  selector:
    app: deploy-latest-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP